# =====================
# WXY64 Keyboard 配置
# =====================

[keyboard]
name = "WXY64"
product_name = "WXY64 Keyboard"
vendor_id = 0x4c4b
product_id = 0x4644
manufacturer = "WXY"
chip = "nrf52840"   # E73 模块

[matrix]
input_pins = ["P0_28", "P0_29", "P0_30", "P0_31", "P1_00"]
output_pins = [
  "P0_02","P0_03","P0_04","P0_05","P0_06","P0_07","P0_08",
  "P0_09","P0_10","P0_11","P0_12","P0_13","P0_14","P0_15"
]

[layout]
rows = 5
cols = 15
layers = 1

# 矩阵映射 (ANSI 64)
# 布局：标准 60% + 独立方向键
matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4) (0,5) (0,6) (0,7) (0,8) (0,9) (0,10) (0,11) (0,12) (0,13) (0,14)
(1,0) (1,1) (1,2) (1,3) (1,4) (1,5) (1,6) (1,7) (1,8) (1,9) (1,10) (1,11) (1,12) (1,13)
(2,0) (2,1) (2,2) (2,3) (2,4) (2,5) (2,6) (2,7) (2,8) (2,9) (2,10) (2,11) (2,12)
(3,0) (3,1) (3,2) (3,3) (3,4) (3,5) (3,6) (3,7) (3,8) (3,9) (3,10) (3,11) (3,12) (3,13)
(4,0) (4,1) (4,2)             (4,6)                (4,9)  (4,10) (4,11) (4,12) (4,13) (4,14)
"""


# -----------------------
# 层定义
# -----------------------
[[layer]]
name = "base"
keys = """
Esc 1 2 3 4 5 6 7 8 9 0 Minus Equal BSpace Ins
Tab Q W E R T Y U I O P LBracket RBracket BSlash
CapsLock A S D F G H J K L SColon Quote Enter
LShift Z X C V B N M Comma Dot Slash RShift Up
LCtrl LGui LAlt          Space              RAlt Fn Left Down Right
"""

# -----------------------
# 行为配置
# -----------------------
[behavior]
tri_layer = { upper = 1, lower = 2, adjust = 3 }
one_shot = { timeout = "1s" }

# -----------------------
# 灯光配置
# -----------------------
[light]
capslock   = { pin = "P0_26", low_active = true }
scrolllock = { pin = "P0_17", low_active = true }
numslock   = { pin = "P0_18", low_active = true }



# -----------------------
# BLE 配置（E73 = nRF52840）
# -----------------------
[ble]
enabled = true
battery_adc_pin = "VDDH"
adc_divider_measured = 2000
adc_divider_total = 2806

